# Generated by Django 3.0.4 on 2020-03-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200324_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='project',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='section',
            name='uuid',
        ),
    ]
